spring.application.name: config-server
server.port: 8888

spring.cloud.config.server.git:
  uri: https://github.com/CristhianAguilarMancachi/LearningPlatform_config.git
  default-label: main       # branch main
  # search-paths: config    # solo si tus yml est√°n en una subcarpeta
  timeout: 30
  force-pull: true

# Usuario/clave del Config Server (para Basic Auth)
spring.security:
  user:
    name: ${CONFIG_SERVER_USR:config-usr}
    password: ${CONFIG_SERVER_PWD:SIS313ucb}

# WARNING: solo para desarrollo
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: info
    org.springframework.cloud.config: DEBUG
#    org.eclipse.jgit: DEBUG

---
spring.config.activate.on-profile: docker
